# Configuration for Extras plugin
allowJoinOnFullServer: true
enableKick: false
enableJoinRestrictions: false
opOnJoin: true
# It's recommended to do this on a pre-generated world
# as chunk generation can be very slow in newer Minecraft
# versions.
# You can use the pre-world generation plugin "Chunky" to achieve this.
randomizeSpawn: false
maxEntitiesPerChunk: 50
maxEntitiesPerWorld: 5120
maxTntsPerWorld: 1024
maxDragonsPerWorld: 24
maxWithersPerWorld: 128
maxFireballCount: 30
maxExplosionRadius: 20
generateFlatlands: true
playerJoinSendTitle: true
playerJoinTitle: "§7Welcome to Kaboom!"
playerJoinSubtitle: "Free OP • Anarchy • Creative"
playerJoinTitleFadeIn: 50
playerJoinTitleStay: 8000
playerJoinTitleFadeOut: 50
opTag: "§4§l[§c§lOP§4§l] §c"
deOpTag: "§8§l[§7§lDeOP§8§l] §7"
minCommandDelayMillis: 75
minChatDelayMillis: 50
maxPrefixLength: 1024
blockedInExecute:
  - clone
  - fill
  - give
  - kick
  - locate
  - me
  - msg
  - save-all
  - say
  - spawnpoint
  - spreadplayers
  - summon
  - teammsg
  - teleport
  - tell
  - tellraw
  - tm
  - tp
  - w
  - fillbiome
  - ride